// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddRelatedFile
{
    internal sealed partial class Vsix
    {
        public const string Id = "AddRelatedFile.250ee36c-eab9-4b63-a779-b6fa1834e1fb";
        public const string Name = "AddRelatedFile";
        public const string Description = @"Add related file";
        public const string Language = "en-GB";
        public const string Version = "1.0";
        public const string Author = "Mark Willmer";
        public const string Tags = "";
    }
}
