// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddRelatedFile
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSPackageCommandFileContextMenuString = "cf77420c-3198-42b5-b6da-9c75c3224ab0";
        public static Guid guidVSPackageCommandFileContextMenu = new Guid(guidVSPackageCommandFileContextMenuString);

        public const string guidVSPackageCommandFileContextMenuCmdSetString = "6b2da8a6-e68b-4068-82eb-2b533d5de2a6";
        public static Guid guidVSPackageCommandFileContextMenuCmdSet = new Guid(guidVSPackageCommandFileContextMenuCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyGroupForCommands = 0x1020;
        public const int AddRelatedCsFileCommandId = 0x0100;
    }
}